from __future__ import annotations

import os
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

from outset_ready.storage import DEFAULT_OWNER_ID, DatabaseTarget, is_postgres_target


class ConfigurationError(RuntimeError):
    pass


@dataclass(frozen=True)
class AppSettings:
    database_target: DatabaseTarget
    owner_email: str
    owner_password_hash: str
    session_secret: str
    secure_cookies: bool
    owner_id: str = DEFAULT_OWNER_ID

    @property
    def persistent_storage(self) -> bool:
        return is_postgres_target(self.database_target)


def load_app_settings(
    environment: Mapping[str, str] | None = None,
    *,
    database_override: DatabaseTarget | None = None,
) -> AppSettings:
    values = os.environ if environment is None else environment
    is_vercel = values.get("VERCEL") == "1"
    database_target = database_override or _database_target(values, is_vercel=is_vercel)
    owner_email = values.get("OUTSET_READY_OWNER_EMAIL", "").strip().casefold()
    owner_password_hash = values.get("OUTSET_READY_OWNER_PASSWORD_HASH", "").strip()
    session_secret = values.get("OUTSET_READY_SESSION_SECRET", "")

    missing = [
        name
        for name, value in (
            ("OUTSET_READY_OWNER_EMAIL", owner_email),
            ("OUTSET_READY_OWNER_PASSWORD_HASH", owner_password_hash),
            ("OUTSET_READY_SESSION_SECRET", session_secret),
        )
        if not value
    ]
    if missing:
        raise ConfigurationError(
            "Missing required application settings: " + ", ".join(missing)
        )
    if "@" not in owner_email:
        raise ConfigurationError("OUTSET_READY_OWNER_EMAIL must be an email address.")
    if not owner_password_hash.startswith("scrypt$"):
        raise ConfigurationError(
            "OUTSET_READY_OWNER_PASSWORD_HASH must be generated by "
            "`outset-ready hash-password`."
        )
    if len(session_secret) < 32:
        raise ConfigurationError(
            "OUTSET_READY_SESSION_SECRET must contain at least 32 characters."
        )
    if is_vercel and not is_postgres_target(database_target):
        raise ConfigurationError(
            "Vercel requires OUTSET_READY_DATABASE_URL, DATABASE_URL or POSTGRES_URL "
            "to point to Postgres. Temporary SQLite is not accepted."
        )

    return AppSettings(
        database_target=database_target,
        owner_email=owner_email,
        owner_password_hash=owner_password_hash,
        session_secret=session_secret,
        secure_cookies=is_vercel or values.get("OUTSET_READY_SECURE_COOKIES") == "1",
    )


def _database_target(values: Mapping[str, str], *, is_vercel: bool) -> DatabaseTarget:
    for name in ("OUTSET_READY_DATABASE_URL", "DATABASE_URL", "POSTGRES_URL"):
        value = values.get(name, "").strip()
        if value:
            return value
    if is_vercel:
        return Path("/tmp/outset_ready.sqlite")
    return Path(values.get("OUTSET_READY_DB_PATH", "data/outset_ready.sqlite")).expanduser()
